### ISSUE TITLE
Is this a good idea? A bad one? 

### ISSUE THREAD

**Issue by bmfay** [AgilionApps/interactor#16]
Howdy @alanpeabody !

I'm wondering if you've drawn any conclusions, some two years later, with respect to "Is this a good idea? A bad one?".   Are you still using the interactor pattern (and leveraging this library for that purpose)?  I continue to value it as a way of making actions modularized/testable/focused/maintainable  but wondered with things being so quiet around here whether you ditched it in favor of another philosophy or if you are continuing to use it despite having (at some point) some desires for improvement (https://github.com/vt-elixir/interactor/issues/13).  I haven't found any of those "pain points" to be particularly painful, but I'd be curious to hear your take now that a considerable amount of time has passed.

Hope you're well!

**Comment by alanpeabody** [comment]
Hey @bmfay!!

Honestly, I haven't had an opportunity to revisit this much. I haven't been doing much writing via Elixir recently.

In general, I really like the "Interactor" approach, although it is probably worth playing with Phoenix's contexts before committing to interactors. https://hexdocs.pm/phoenix/contexts.html

In regards to this particular PR I absolutely think it is the right direction - but maybe not the right interface? The concept of a struct holding state while going through a set of manipulations is a pretty robust pattern in elixir. Ecto.Changeset, Ecto.Multi and Plug.Conn are all extremely common examples. By using a struct you take away some of the "what arguments do I get" and adopt a standard. I also think the explicit pipeline of calls is much more "elixiry" then callbacks, not to mention more flexible.

**Comment by bmfay** [comment]
Agreed re: "struct holding state while going through a set of manipulations is a pretty robust pattern".  Started to look into Phoenix contexts, seems worth exploring, so I may see how I like it on a new project.  Be sure to let me know if you are back in the Elixir world at some point!

**Comment by alanpeabody** [comment]
@bmfay great talk discussing basically this approach: https://www.youtube.com/watch?v=ycpNi701aCs
